services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_VERIFICATION_TOKEN: ${NOTION_VERIFICATION_TOKEN}
    restart: unless-stopped
